filter:
    excluded_paths:
        - '.github/*'
        - 'tests/*'
        - 'bin/*'
        - 'docs/*'
    dependency_paths:
        - 'wordpress/'
tools:
    external_code_coverage: false
    php_code_sniffer:
        config:
            standard: WordPress
    sensiolabs_security_checker: true
    php_sim: true # PHP Similarity Analyzer

build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run

checks:
    php:
        verify_property_names: false
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: false
        unused_variables: true
        unused_properties: false
        unused_parameters: false
        unused_methods: false
        unreachable_code: false
        too_many_arguments: true
        symfony_request_injection: false
        switch_fallthrough_commented: false
        sql_injection_vulnerabilities: false
        security_vulnerabilities: false
        return_in_constructor: true
        require_scope_for_methods: true
        require_php_tag_first: true
        property_assignments: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parse_doc_comments: false
        parameter_non_unique: true
        overriding_private_members: true
        overriding_parameter: true
        non_commented_empty_catch_block: false
        no_trait_type_hints: false
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_exit: false
        no_eval: false
        no_error_suppression: false
        no_debug_code: true
        missing_arguments: true
        method_calls_on_non_object: true
        instanceof_class_exists: false
        foreach_usable_as_reference: false
        foreach_traversable: true
        fix_doc_comments: false
        encourage_shallow_comparison: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: false
        comparison_always_same_result: true
        code_rating: false
        closure_use_not_conflicting: false
        closure_use_modifiable: false
        catch_class_exists: false
        call_to_parent_method: true
        avoid_superglobals: false
        avoid_length_functions_in_loops: true
        avoid_entity_manager_injection: false
        avoid_duplicate_types: false
        avoid_closing_tag: true
        assignment_of_null_return: true
        argument_type_checks: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '5'
        no_long_variable_names:
            maximum: '20'
        fix_line_ending: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: false
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: true
                concatenation: true
                negation: true
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: true
                else_on_new_line: false
            for:
                opening: end-of-line
                always: true
            while:
                opening: end-of-line
                always: true
            do_while:
                opening: end-of-line
                always: true
                while_on_new_line: false
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower